# Generated by Django 5.1.6 on 2025-08-25 10:16

import blog.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=blog.storages.OverwriteS3Storage(), upload_to='post_images/'),
        ),
    ]
