# Generated by Django 5.1.6 on 2025-09-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='product_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
