# Generated by Django 5.1.6 on 2025-06-29 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('light', models.CharField(max_length=100)),
                ('water', models.CharField(max_length=300)),
                ('temperature', models.CharField(max_length=100)),
                ('humidity', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('care_info', models.JSONField(blank=True, null=True)),
                ('fertilizer', models.CharField(blank=True, max_length=300, null=True)),
                ('pests', models.CharField(blank=True, max_length=300, null=True)),
                ('pruning', models.CharField(blank=True, max_length=300, null=True)),
                ('repotting', models.CharField(blank=True, max_length=300, null=True)),
                ('delivery', models.CharField(blank=True, max_length=300, null=True)),
                ('planting', models.CharField(blank=True, max_length=300, null=True)),
                ('harvesting', models.CharField(blank=True, max_length=300, null=True)),
                ('size', models.CharField(blank=True, max_length=300, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
            ],
        ),
    ]
