# Generated by Django 5.1.6 on 2025-07-30 12:10

import products.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(storage=products.storages.OverwriteS3Storage(), upload_to='media/products/'),
        ),
    ]
