# Generated by Django 5.1.6 on 2025-08-25 10:16

import products.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(storage=products.storages.OverwriteS3Storage(), upload_to='products/'),
        ),
    ]
