# Generated by Django 5.1.6 on 2025-09-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_color',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
