# Generated by Django 5.1.6 on 2025-06-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='has_colors',
            field=models.BooleanField(default=False),
        ),
    ]
